[package]
name = "bottles-plugin-host"
description = "Wasm plugin host for Bottles Next"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
bottles-core.workspace = true
async-trait.workspace = true
futures = { version = "0.3", default-features = false, features = ["std"] }
serde.workspace = true
toml = "0.9.10"
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tokio-stream = { workspace = true, features = ["sync"] }
url.workspace = true
wasmtime = { version = "49", default-features = false, features = ["async", "cache", "component-model", "component-model-async", "cranelift"] }
wasmtime-wasi = { version = "49", default-features = false, features = ["p3"] }
wasmtime-wasi-http = { version = "49", default-features = false, features = ["default-send-request", "p3"] }

[build-dependencies]
heck = "0.5"
wit-parser = { version = "0.259", default-features = false, features = ["std"] }
