[package]
name = "bottles-plugin-host"
description = "Wasm plugin host for Bottles Next"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-fs.workspace = true
uuid.workspace = true
blocking.workspace = true
futures = { version = "0.3", default-features = false, features = ["std"] }
serde.workspace = true
semver.workspace = true
thiserror.workspace = true
toml = "0.9.10"
tokio = { workspace = true, features = ["sync"] }
url = { workspace = true, features = ["serde"] }
wasmtime = { version = "49", default-features = false, features = ["async", "component-model", "component-model-async", "cranelift"] }
wasmtime-wasi = { version = "49", default-features = false, features = ["p3"] }
wasmtime-wasi-http = { version = "49", default-features = false, features = ["default-send-request", "p3"] }
